#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Industrial_MiningCart_01_A

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Industrial_MiningCart_01_A.Apollo_Industrial_MiningCart_01_A_C
// 0x0000 (0x0E70 - 0x0E70)
class AApollo_Industrial_MiningCart_01_A_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_Industrial_MiningCart_01_A_C">();
	}
	static class AApollo_Industrial_MiningCart_01_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Industrial_MiningCart_01_A_C>();
	}
};
static_assert(alignof(AApollo_Industrial_MiningCart_01_A_C) == 0x000008, "Wrong alignment on AApollo_Industrial_MiningCart_01_A_C");
static_assert(sizeof(AApollo_Industrial_MiningCart_01_A_C) == 0x000E70, "Wrong size on AApollo_Industrial_MiningCart_01_A_C");

}

