#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Artemis_Custom_KillVolume_Milkshake

#include "Basic.hpp"

#include "Artemis_Custom_KillVolume_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Artemis_Custom_KillVolume_Milkshake.Artemis_Custom_KillVolume_Milkshake_C
// 0x0000 (0x02B0 - 0x02B0)
class AArtemis_Custom_KillVolume_Milkshake_C final : public AArtemis_Custom_KillVolume_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Artemis_Custom_KillVolume_Milkshake_C">();
	}
	static class AArtemis_Custom_KillVolume_Milkshake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AArtemis_Custom_KillVolume_Milkshake_C>();
	}
};
static_assert(alignof(AArtemis_Custom_KillVolume_Milkshake_C) == 0x000008, "Wrong alignment on AArtemis_Custom_KillVolume_Milkshake_C");
static_assert(sizeof(AArtemis_Custom_KillVolume_Milkshake_C) == 0x0002B0, "Wrong size on AArtemis_Custom_KillVolume_Milkshake_C");

}

