#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaMainMenuLeaveButton

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaMainMenuLeaveButton.AthenaMainMenuLeaveButton_C
// 0x0000 (0x1180 - 0x1180)
class UAthenaMainMenuLeaveButton_C final : public UFortMainMenuLeaveButton
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaMainMenuLeaveButton_C">();
	}
	static class UAthenaMainMenuLeaveButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaMainMenuLeaveButton_C>();
	}
};
static_assert(alignof(UAthenaMainMenuLeaveButton_C) == 0x000010, "Wrong alignment on UAthenaMainMenuLeaveButton_C");
static_assert(sizeof(UAthenaMainMenuLeaveButton_C) == 0x001180, "Wrong size on UAthenaMainMenuLeaveButton_C");

}

