#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_BuildingProp_Explosive

#include "Basic.hpp"

#include "Athena_BuildingProp_Explosive_classes.hpp"
#include "Athena_BuildingProp_Explosive_parameters.hpp"


namespace SDK
{

// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ApplyDamageToActor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor_to_Damage                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::ApplyDamageToActor(class AActor* Actor_to_Damage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ApplyDamageToActor");

	Params::Athena_BuildingProp_Explosive_C_ApplyDamageToActor Parms{};

	Parms.Actor_to_Damage = Actor_to_Damage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.DeactivateEmitter
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::DeactivateEmitter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "DeactivateEmitter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.DestroyHitActors
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           HitActor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::DestroyHitActors(class AActor* HitActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "DestroyHitActors");

	Params::Athena_BuildingProp_Explosive_C_DestroyHitActors Parms{};

	Parms.HitActor = HitActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ExecuteExplosionOnActor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ActorToExplode                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::ExecuteExplosionOnActor(class AActor* ActorToExplode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ExecuteExplosionOnActor");

	Params::Athena_BuildingProp_Explosive_C_ExecuteExplosionOnActor Parms{};

	Parms.ActorToExplode = ActorToExplode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ExecuteFireApplicationInRadiusIfCurieEnabled
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           FireApplicationTarget                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::ExecuteFireApplicationInRadiusIfCurieEnabled(class AActor* FireApplicationTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ExecuteFireApplicationInRadiusIfCurieEnabled");

	Params::Athena_BuildingProp_Explosive_C_ExecuteFireApplicationInRadiusIfCurieEnabled Parms{};

	Parms.FireApplicationTarget = FireApplicationTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ExecuteUbergraph_Athena_BuildingProp_Explosive
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::ExecuteUbergraph_Athena_BuildingProp_Explosive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ExecuteUbergraph_Athena_BuildingProp_Explosive");

	Params::Athena_BuildingProp_Explosive_C_ExecuteUbergraph_Athena_BuildingProp_Explosive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ExplodeAndDie
// (BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::ExplodeAndDie()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ExplodeAndDie");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ExplodeAndDieStaggered
// (BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::ExplodeAndDieStaggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ExplodeAndDieStaggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ExplosionTrace
// (BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::ExplosionTrace()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ExplosionTrace");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.FastExplodeAndDie
// (BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::FastExplodeAndDie()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "FastExplodeAndDie");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.GrowTimeline
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::GrowTimeline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "GrowTimeline");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.LaunchActor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor_To_Launch                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::LaunchActor(class AActor* Actor_To_Launch)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "LaunchActor");

	Params::Athena_BuildingProp_Explosive_C_LaunchActor Parms{};

	Parms.Actor_To_Launch = Actor_To_Launch;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ManuallyTriggerFuse
// (BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::ManuallyTriggerFuse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ManuallyTriggerFuse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.MinigameIsInProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IgnoreWarmUp                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    HasValidMinigame                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsRunning                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::MinigameIsInProgress(bool IgnoreWarmUp, bool* HasValidMinigame, bool* IsRunning)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "MinigameIsInProgress");

	Params::Athena_BuildingProp_Explosive_C_MinigameIsInProgress Parms{};

	Parms.IgnoreWarmUp = IgnoreWarmUp;

	UObject::ProcessEvent(Func, &Parms);

	if (HasValidMinigame != nullptr)
		*HasValidMinigame = Parms.HasValidMinigame;

	if (IsRunning != nullptr)
		*IsRunning = Parms.IsRunning;
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnCompletion
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    WasCancelled                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::OnCompletion(bool WasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnCompletion");

	Params::Athena_BuildingProp_Explosive_C_OnCompletion Parms{};

	Parms.WasCancelled = WasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnCurieElementInteract_BP
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FCurieContainerHandle            CurieContainerHandle                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     ElementTag                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FCurieInteractParamsHandle       InteractParamsHandle                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void AAthena_BuildingProp_Explosive_C::OnCurieElementInteract_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag, const struct FCurieInteractParamsHandle& InteractParamsHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnCurieElementInteract_BP");

	Params::Athena_BuildingProp_Explosive_C_OnCurieElementInteract_BP Parms{};

	Parms.CurieContainerHandle = std::move(CurieContainerHandle);
	Parms.ElementTag = std::move(ElementTag);
	Parms.InteractParamsHandle = std::move(InteractParamsHandle);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnCurieElementInteractBegun_BP
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FCurieContainerHandle            CurieContainerHandle                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     ElementTag                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FCurieInteractParamsHandle       InteractParamsHandle                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void AAthena_BuildingProp_Explosive_C::OnCurieElementInteractBegun_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag, const struct FCurieInteractParamsHandle& InteractParamsHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnCurieElementInteractBegun_BP");

	Params::Athena_BuildingProp_Explosive_C_OnCurieElementInteractBegun_BP Parms{};

	Parms.CurieContainerHandle = std::move(CurieContainerHandle);
	Parms.ElementTag = std::move(ElementTag);
	Parms.InteractParamsHandle = std::move(InteractParamsHandle);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnDamageServer
// (BlueprintAuthorityOnly, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            DamageTags                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FVector                          Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayEffectContextHandle     EffectContext                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void AAthena_BuildingProp_Explosive_C::OnDamageServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnDamageServer");

	Params::Athena_BuildingProp_Explosive_C_OnDamageServer Parms{};

	Parms.Damage = Damage;
	Parms.DamageTags = std::move(DamageTags);
	Parms.Momentum = std::move(Momentum);
	Parms.HitInfo = std::move(HitInfo);
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.EffectContext = std::move(EffectContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnDeathPlayEffects
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            DamageTags                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FVector                          Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AFortPawn*                        InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayEffectContextHandle     EffectContext                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void AAthena_BuildingProp_Explosive_C::OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnDeathPlayEffects");

	Params::Athena_BuildingProp_Explosive_C_OnDeathPlayEffects Parms{};

	Parms.Damage = Damage;
	Parms.DamageTags = std::move(DamageTags);
	Parms.Momentum = std::move(Momentum);
	Parms.HitInfo = std::move(HitInfo);
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.EffectContext = std::move(EffectContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnDeathServer
// (BlueprintAuthorityOnly, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            DamageTags                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FVector                          Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayEffectContextHandle     EffectContext                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void AAthena_BuildingProp_Explosive_C::OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnDeathServer");

	Params::Athena_BuildingProp_Explosive_C_OnDeathServer Parms{};

	Parms.Damage = Damage;
	Parms.DamageTags = std::move(DamageTags);
	Parms.Momentum = std::move(Momentum);
	Parms.HitInfo = std::move(HitInfo);
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.EffectContext = std::move(EffectContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnFireFx
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::OnFireFx()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnFireFx");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnRep_DamageStateNotify
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::OnRep_DamageStateNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnRep_DamageStateNotify");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.OnRep_ExplosiveFxRepNotify
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::OnRep_ExplosiveFxRepNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "OnRep_ExplosiveFxRepNotify");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ShouldCancelExplosion
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_BuildingProp_Explosive_C::ShouldCancelExplosion(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ShouldCancelExplosion");

	Params::Athena_BuildingProp_Explosive_C_ShouldCancelExplosion Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.ShouldDie
// (BlueprintAuthorityOnly, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      EventInstigator                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AAthena_BuildingProp_Explosive_C::ShouldDie(float Damage, class AController* EventInstigator, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "ShouldDie");

	Params::Athena_BuildingProp_Explosive_C_ShouldDie Parms{};

	Parms.Damage = Damage;
	Parms.EventInstigator = EventInstigator;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.StartDetonation
// (BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::StartDetonation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "StartDetonation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.StopGrowAudio
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::StopGrowAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "StopGrowAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.TriggeredByGasPump
// (BlueprintCallable, BlueprintEvent)

void AAthena_BuildingProp_Explosive_C::TriggeredByGasPump()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "TriggeredByGasPump");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_BuildingProp_Explosive.Athena_BuildingProp_Explosive_C.BlueprintCanAttemptGenerateResources
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FGameplayTagContainer            InTags                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class AController*                      InstigatorController                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AAthena_BuildingProp_Explosive_C::BlueprintCanAttemptGenerateResources(const struct FGameplayTagContainer& InTags, class AController* InstigatorController) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Athena_BuildingProp_Explosive_C", "BlueprintCanAttemptGenerateResources");

	Params::Athena_BuildingProp_Explosive_C_BlueprintCanAttemptGenerateResources Parms{};

	Parms.InTags = std::move(InTags);
	Parms.InstigatorController = InstigatorController;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

