#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_VehicleSpawner_OctopusV2

#include "Basic.hpp"

#include "Athena_VehicleSpawner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_VehicleSpawner_OctopusV2.Athena_VehicleSpawner_OctopusV2_C
// 0x0008 (0x0308 - 0x0300)
class AAthena_VehicleSpawner_OctopusV2_C : public AAthena_VehicleSpawner_C
{
public:
	class UTextRenderComponent*                   TextRender;                                        // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_VehicleSpawner_OctopusV2_C">();
	}
	static class AAthena_VehicleSpawner_OctopusV2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_VehicleSpawner_OctopusV2_C>();
	}
};
static_assert(alignof(AAthena_VehicleSpawner_OctopusV2_C) == 0x000008, "Wrong alignment on AAthena_VehicleSpawner_OctopusV2_C");
static_assert(sizeof(AAthena_VehicleSpawner_OctopusV2_C) == 0x000308, "Wrong size on AAthena_VehicleSpawner_OctopusV2_C");
static_assert(offsetof(AAthena_VehicleSpawner_OctopusV2_C, TextRender) == 0x000300, "Member 'AAthena_VehicleSpawner_OctopusV2_C::TextRender' has a wrong offset!");

}

