#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Trap_Context_Reinforced_Athena

#include "Basic.hpp"

#include "B_Trap_Context_Reinforced_Athena_classes.hpp"
#include "B_Trap_Context_Reinforced_Athena_parameters.hpp"


namespace SDK
{

// Function B_Trap_Context_Reinforced_Athena.B_Trap_Context_Reinforced_Athena_C.ExecuteUbergraph_B_Trap_Context_Reinforced_Athena
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Trap_Context_Reinforced_Athena_C::ExecuteUbergraph_B_Trap_Context_Reinforced_Athena(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Trap_Context_Reinforced_Athena_C", "ExecuteUbergraph_B_Trap_Context_Reinforced_Athena");

	Params::B_Trap_Context_Reinforced_Athena_C_ExecuteUbergraph_B_Trap_Context_Reinforced_Athena Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Trap_Context_Reinforced_Athena.B_Trap_Context_Reinforced_Athena_C.OnAttachToBuilding
// (Event, Public, BlueprintEvent)
// Parameters:
// class ABuildingActor*                   AttachedToBuilding                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Trap_Context_Reinforced_Athena_C::OnAttachToBuilding(class ABuildingActor* AttachedToBuilding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Trap_Context_Reinforced_Athena_C", "OnAttachToBuilding");

	Params::B_Trap_Context_Reinforced_Athena_C_OnAttachToBuilding Parms{};

	Parms.AttachedToBuilding = AttachedToBuilding;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Trap_Context_Reinforced_Athena.B_Trap_Context_Reinforced_Athena_C.SetHealthImmediately
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void AB_Trap_Context_Reinforced_Athena_C::SetHealthImmediately()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Trap_Context_Reinforced_Athena_C", "SetHealthImmediately");

	UObject::ProcessEvent(Func, nullptr);
}

}

