#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Back

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Back.Back_C
// 0x0000 (0x01A0 - 0x01A0)
class UBack_C final : public UFortConversationTaskNode_Back
{
public:
	struct FConversationTaskResult ExecuteTaskNode(const struct FConversationContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Back_C">();
	}
	static class UBack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBack_C>();
	}
};
static_assert(alignof(UBack_C) == 0x000008, "Wrong alignment on UBack_C");
static_assert(sizeof(UBack_C) == 0x0001A0, "Wrong size on UBack_C");

}

