#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_S21WaterFall_GamePlay_C

#include "Basic.hpp"

#include "BP_WaterfallGamePlay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_S21WaterFall_GamePlay_C.BP_S21WaterFall_GamePlay_C_C
// 0x0000 (0x0518 - 0x0518)
class ABP_S21WaterFall_GamePlay_C_C final : public ABP_WaterfallGamePlay_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_S21WaterFall_GamePlay_C_C">();
	}
	static class ABP_S21WaterFall_GamePlay_C_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_S21WaterFall_GamePlay_C_C>();
	}
};
static_assert(alignof(ABP_S21WaterFall_GamePlay_C_C) == 0x000008, "Wrong alignment on ABP_S21WaterFall_GamePlay_C_C");
static_assert(sizeof(ABP_S21WaterFall_GamePlay_C_C) == 0x000518, "Wrong size on ABP_S21WaterFall_GamePlay_C_C");

}

