#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkewedTabButton

#include "Basic.hpp"

#include "BP_SkewedTabButton_classes.hpp"
#include "BP_SkewedTabButton_parameters.hpp"


namespace SDK
{

// Function BP_SkewedTabButton.BP_SkewedTabButton_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UBP_SkewedTabButton_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkewedTabButton_C", "BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkewedTabButton.BP_SkewedTabButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBP_SkewedTabButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkewedTabButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkewedTabButton.BP_SkewedTabButton_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UBP_SkewedTabButton_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkewedTabButton_C", "BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkewedTabButton.BP_SkewedTabButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBP_SkewedTabButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkewedTabButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkewedTabButton.BP_SkewedTabButton_C.ExecuteUbergraph_BP_SkewedTabButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SkewedTabButton_C::ExecuteUbergraph_BP_SkewedTabButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkewedTabButton_C", "ExecuteUbergraph_BP_SkewedTabButton");

	Params::BP_SkewedTabButton_C_ExecuteUbergraph_BP_SkewedTabButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkewedTabButton.BP_SkewedTabButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SkewedTabButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkewedTabButton_C", "PreConstruct");

	Params::BP_SkewedTabButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

