#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_CycleArrow_Right_Double

#include "Basic.hpp"

#include "ButtonStyle_MediumTransparentNoCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle_CycleArrow_Right_Double.ButtonStyle_CycleArrow_Right_Double_C
// 0x0000 (0x0730 - 0x0730)
class UButtonStyle_CycleArrow_Right_Double_C final : public UButtonStyle_MediumTransparentNoCues_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle_CycleArrow_Right_Double_C">();
	}
	static class UButtonStyle_CycleArrow_Right_Double_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_CycleArrow_Right_Double_C>();
	}
};
static_assert(alignof(UButtonStyle_CycleArrow_Right_Double_C) == 0x000010, "Wrong alignment on UButtonStyle_CycleArrow_Right_Double_C");
static_assert(sizeof(UButtonStyle_CycleArrow_Right_Double_C) == 0x000730, "Wrong size on UButtonStyle_CycleArrow_Right_Double_C");

}

