#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Skew_SocialInteraction

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Skew_SocialInteraction.ButtonStyle-Skew_SocialInteraction_C
// 0x0000 (0x0730 - 0x0730)
class UButtonStyle_Skew_SocialInteraction_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Skew_SocialInteraction_C">();
	}
	static class UButtonStyle_Skew_SocialInteraction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Skew_SocialInteraction_C>();
	}
};
static_assert(alignof(UButtonStyle_Skew_SocialInteraction_C) == 0x000010, "Wrong alignment on UButtonStyle_Skew_SocialInteraction_C");
static_assert(sizeof(UButtonStyle_Skew_SocialInteraction_C) == 0x000730, "Wrong size on UButtonStyle_Skew_SocialInteraction_C");

}

