#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENUM_PlayEmote_EmoteDefinition

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ENUM_PlayEmote_EmoteDefinition.ENUM_PlayEmote_EmoteDefinition
// NumValues: 0x0006
enum class ENUM_PlayEmote_EmoteDefinition : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	ENUM_PlayEmote_MAX                       = 5,
};

}

