#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortFeatUpdateEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortFeatUpdateEntry.FortFeatUpdateEntry_C
// 0x0010 (0x0380 - 0x0370)
class UFortFeatUpdateEntry_C final : public UFortFeatUpdateEntry
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Intro;                                             // 0x0378(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FortFeatUpdateEntry(int32 EntryPoint);
	void OnInitialized();
	void StartQuestIntro();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortFeatUpdateEntry_C">();
	}
	static class UFortFeatUpdateEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortFeatUpdateEntry_C>();
	}
};
static_assert(alignof(UFortFeatUpdateEntry_C) == 0x000010, "Wrong alignment on UFortFeatUpdateEntry_C");
static_assert(sizeof(UFortFeatUpdateEntry_C) == 0x000380, "Wrong size on UFortFeatUpdateEntry_C");
static_assert(offsetof(UFortFeatUpdateEntry_C, UberGraphFrame) == 0x000370, "Member 'UFortFeatUpdateEntry_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UFortFeatUpdateEntry_C, Intro) == 0x000378, "Member 'UFortFeatUpdateEntry_C::Intro' has a wrong offset!");

}

