#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_ShieldGenerator_ThrowProjectile_Secondary

#include "Basic.hpp"

#include "GA_Athena_Consumable_Throw_Secondary_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_ShieldGenerator_ThrowProjectile_Secondary.GA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C
// 0x0000 (0x0F10 - 0x0F10)
class UGA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C final : public UGA_Athena_Consumable_Throw_Secondary_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C">();
	}
	static class UGA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C>();
	}
};
static_assert(alignof(UGA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C) == 0x000008, "Wrong alignment on UGA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C");
static_assert(sizeof(UGA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C) == 0x000F10, "Wrong size on UGA_Athena_ShieldGenerator_ThrowProjectile_Secondary_C");

}

