#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_GrappleGloves_InSwingingMovementMode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_WestSausage_InSwingingMovementMode_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_GrappleGloves_InSwingingMovementMode.GA_GrappleGloves_InSwingingMovementMode_C
// 0x0010 (0x0B48 - 0x0B38)
class UGA_GrappleGloves_InSwingingMovementMode_C final : public UGA_WestSausage_InSwingingMovementMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_GrappleGloves_InSwingingMovementMode_C; // 0x0B38(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABuildingGameplayActor*                 BGA;                                               // 0x0B40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_GrappleGloves_InSwingingMovementMode(int32 EntryPoint);
	void FailedToActivatePassiveAbility();
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_GrappleGloves_InSwingingMovementMode_C">();
	}
	static class UGA_GrappleGloves_InSwingingMovementMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_GrappleGloves_InSwingingMovementMode_C>();
	}
};
static_assert(alignof(UGA_GrappleGloves_InSwingingMovementMode_C) == 0x000008, "Wrong alignment on UGA_GrappleGloves_InSwingingMovementMode_C");
static_assert(sizeof(UGA_GrappleGloves_InSwingingMovementMode_C) == 0x000B48, "Wrong size on UGA_GrappleGloves_InSwingingMovementMode_C");
static_assert(offsetof(UGA_GrappleGloves_InSwingingMovementMode_C, UberGraphFrame_GA_GrappleGloves_InSwingingMovementMode_C) == 0x000B38, "Member 'UGA_GrappleGloves_InSwingingMovementMode_C::UberGraphFrame_GA_GrappleGloves_InSwingingMovementMode_C' has a wrong offset!");
static_assert(offsetof(UGA_GrappleGloves_InSwingingMovementMode_C, BGA) == 0x000B40, "Member 'UGA_GrappleGloves_InSwingingMovementMode_C::BGA' has a wrong offset!");

}

