#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_NPC_Player_Irwin_Nug_DirectDamage

#include "Basic.hpp"

#include "GE_NPC_Parent_DirectDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_NPC_Player_Irwin_Nug_DirectDamage.GE_NPC_Player_Irwin_Nug_DirectDamage_C
// 0x0000 (0x07F8 - 0x07F8)
class UGE_NPC_Player_Irwin_Nug_DirectDamage_C final : public UGE_NPC_Parent_DirectDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_NPC_Player_Irwin_Nug_DirectDamage_C">();
	}
	static class UGE_NPC_Player_Irwin_Nug_DirectDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_NPC_Player_Irwin_Nug_DirectDamage_C>();
	}
};
static_assert(alignof(UGE_NPC_Player_Irwin_Nug_DirectDamage_C) == 0x000008, "Wrong alignment on UGE_NPC_Player_Irwin_Nug_DirectDamage_C");
static_assert(sizeof(UGE_NPC_Player_Irwin_Nug_DirectDamage_C) == 0x0007F8, "Wrong size on UGE_NPC_Player_Irwin_Nug_DirectDamage_C");

}

