#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mansion_Vase_03

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mansion_Vase_03.Mansion_Vase_03_C
// 0x0000 (0x0E70 - 0x0E70)
class AMansion_Vase_03_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Mansion_Vase_03_C">();
	}
	static class AMansion_Vase_03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMansion_Vase_03_C>();
	}
};
static_assert(alignof(AMansion_Vase_03_C) == 0x000008, "Wrong alignment on AMansion_Vase_03_C");
static_assert(sizeof(AMansion_Vase_03_C) == 0x000E70, "Wrong size on AMansion_Vase_03_C");

}

