#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Parallel_BigDesk

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Parallel_BigDesk.Parallel_BigDesk_C
// 0x0000 (0x0E70 - 0x0E70)
class AParallel_BigDesk_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Parallel_BigDesk_C">();
	}
	static class AParallel_BigDesk_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AParallel_BigDesk_C>();
	}
};
static_assert(alignof(AParallel_BigDesk_C) == 0x000008, "Wrong alignment on AParallel_BigDesk_C");
static_assert(sizeof(AParallel_BigDesk_C) == 0x000E70, "Wrong size on AParallel_BigDesk_C");

}

