#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuartzMusicTrackComponent_Inner

#include "Basic.hpp"

#include "QuartzMusicTrackComponent_DataTracker_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass QuartzMusicTrackComponent_Inner.QuartzMusicTrackComponent_Inner_C
// 0x0000 (0x01D0 - 0x01D0)
class UQuartzMusicTrackComponent_Inner_C final : public UQuartzMusicTrackComponent_DataTracker_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"QuartzMusicTrackComponent_Inner_C">();
	}
	static class UQuartzMusicTrackComponent_Inner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuartzMusicTrackComponent_Inner_C>();
	}
};
static_assert(alignof(UQuartzMusicTrackComponent_Inner_C) == 0x000008, "Wrong alignment on UQuartzMusicTrackComponent_Inner_C");
static_assert(sizeof(UQuartzMusicTrackComponent_Inner_C) == 0x0001D0, "Wrong size on UQuartzMusicTrackComponent_Inner_C");

}

