#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RollTheDice

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RollTheDice.RollTheDice_C
// 0x0000 (0x0248 - 0x0248)
class URollTheDice_C final : public UFortConversationTaskNode_DataDrivenService
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RollTheDice_C">();
	}
	static class URollTheDice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URollTheDice_C>();
	}
};
static_assert(alignof(URollTheDice_C) == 0x000008, "Wrong alignment on URollTheDice_C");
static_assert(sizeof(URollTheDice_C) == 0x000248, "Wrong size on URollTheDice_C");

}

