#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shelters_Stove02

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Shelters_Stove02.Shelters_Stove02_C
// 0x0000 (0x0E70 - 0x0E70)
class AShelters_Stove02_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Shelters_Stove02_C">();
	}
	static class AShelters_Stove02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShelters_Stove02_C>();
	}
};
static_assert(alignof(AShelters_Stove02_C) == 0x000008, "Wrong alignment on AShelters_Stove02_C");
static_assert(sizeof(AShelters_Stove02_C) == 0x000E70, "Wrong size on AShelters_Stove02_C");

}

