#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarLfgStateWidget

#include "Basic.hpp"

#include "SidebarLfgStateWidget_classes.hpp"
#include "SidebarLfgStateWidget_parameters.hpp"


namespace SDK
{

// Function SidebarLfgStateWidget.SidebarLfgStateWidget_C.BndEvt__SidebarLfgStateWidget_StateActionButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonLegacy*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarLfgStateWidget_C::BndEvt__SidebarLfgStateWidget_StateActionButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarLfgStateWidget_C", "BndEvt__SidebarLfgStateWidget_StateActionButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");

	Params::SidebarLfgStateWidget_C_BndEvt__SidebarLfgStateWidget_StateActionButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarLfgStateWidget.SidebarLfgStateWidget_C.ChangeIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELfgState                               LfgState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarLfgStateWidget_C::ChangeIcon(ELfgState LfgState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarLfgStateWidget_C", "ChangeIcon");

	Params::SidebarLfgStateWidget_C_ChangeIcon Parms{};

	Parms.LfgState = LfgState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarLfgStateWidget.SidebarLfgStateWidget_C.ExecuteUbergraph_SidebarLfgStateWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarLfgStateWidget_C::ExecuteUbergraph_SidebarLfgStateWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarLfgStateWidget_C", "ExecuteUbergraph_SidebarLfgStateWidget");

	Params::SidebarLfgStateWidget_C_ExecuteUbergraph_SidebarLfgStateWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarLfgStateWidget.SidebarLfgStateWidget_C.UpdateButtonInteractability
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELfgState                               ELfgState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarLfgStateWidget_C::UpdateButtonInteractability(ELfgState ELfgState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarLfgStateWidget_C", "UpdateButtonInteractability");

	Params::SidebarLfgStateWidget_C_UpdateButtonInteractability Parms{};

	Parms.ELfgState = ELfgState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarLfgStateWidget.SidebarLfgStateWidget_C.UpdateStateData
// (Event, Protected, BlueprintEvent)
// Parameters:
// ELfgState                               CurrState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarLfgStateWidget_C::UpdateStateData(ELfgState CurrState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarLfgStateWidget_C", "UpdateStateData");

	Params::SidebarLfgStateWidget_C_UpdateStateData Parms{};

	Parms.CurrState = CurrState;

	UObject::ProcessEvent(Func, &Parms);
}

}

