#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SOGB_PlayEmote

#include "Basic.hpp"

#include "SOGB_PlayEmote_classes.hpp"
#include "SOGB_PlayEmote_parameters.hpp"


namespace SDK
{

// Function SOGB_PlayEmote.SOGB_PlayEmote_C.ExecuteUbergraph_SOGB_PlayEmote
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USOGB_PlayEmote_C::ExecuteUbergraph_SOGB_PlayEmote(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "ExecuteUbergraph_SOGB_PlayEmote");

	Params::SOGB_PlayEmote_C_ExecuteUbergraph_SOGB_PlayEmote Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.GetDifferentRandomEmoteIndexFromList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   LastEmoteIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 USOGB_PlayEmote_C::GetDifferentRandomEmoteIndexFromList(int32 LastEmoteIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "GetDifferentRandomEmoteIndexFromList");

	Params::SOGB_PlayEmote_C_GetDifferentRandomEmoteIndexFromList Parms{};

	Parms.LastEmoteIndex = LastEmoteIndex;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.Init
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Avatar                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UGameplayBehaviorConfig*          Config                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsValid                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USOGB_PlayEmote_C::Init(class ACharacter* Avatar, class UGameplayBehaviorConfig* Config, bool* IsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "Init");

	Params::SOGB_PlayEmote_C_Init Parms{};

	Parms.Avatar = Avatar;
	Parms.Config = Config;

	UObject::ProcessEvent(Func, &Parms);

	if (IsValid != nullptr)
		*IsValid = Parms.IsValid;
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.K2_OnFinishedCharacter
// (Event, Public, BlueprintEvent)
// Parameters:
// class ACharacter*                       Avatar                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasInterrupted                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USOGB_PlayEmote_C::K2_OnFinishedCharacter(class ACharacter* Avatar, bool bWasInterrupted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "K2_OnFinishedCharacter");

	Params::SOGB_PlayEmote_C_K2_OnFinishedCharacter Parms{};

	Parms.Avatar = Avatar;
	Parms.bWasInterrupted = bWasInterrupted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.K2_OnTriggeredCharacter
// (Event, Public, BlueprintEvent)
// Parameters:
// class ACharacter*                       Avatar                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UGameplayBehaviorConfig*          Config                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           SmartObjectOwner                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USOGB_PlayEmote_C::K2_OnTriggeredCharacter(class ACharacter* Avatar, const class UGameplayBehaviorConfig* Config, class AActor* SmartObjectOwner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "K2_OnTriggeredCharacter");

	Params::SOGB_PlayEmote_C_K2_OnTriggeredCharacter Parms{};

	Parms.Avatar = Avatar;
	Parms.Config = Config;
	Parms.SmartObjectOwner = SmartObjectOwner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.OnFinish_35C2562246D51231FC320E8A29D8D9E0
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::OnFinish_35C2562246D51231FC320E8A29D8D9E0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "OnFinish_35C2562246D51231FC320E8A29D8D9E0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.OnFinish_4067E4514CA66085F91A8BB2796DF3C6
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::OnFinish_4067E4514CA66085F91A8BB2796DF3C6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "OnFinish_4067E4514CA66085F91A8BB2796DF3C6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.OnFinish_744EEC97426E44C05D778E9828E19A44
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::OnFinish_744EEC97426E44C05D778E9828E19A44()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "OnFinish_744EEC97426E44C05D778E9828E19A44");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.OnFinish_BB6D0D9942BB12EEB43FCAB929A423C0
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::OnFinish_BB6D0D9942BB12EEB43FCAB929A423C0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "OnFinish_BB6D0D9942BB12EEB43FCAB929A423C0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.OnFinish_EF1050CD4A4EEACD2A28D5B3563FCF37
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::OnFinish_EF1050CD4A4EEACD2A28D5B3563FCF37()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "OnFinish_EF1050CD4A4EEACD2A28D5B3563FCF37");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.OnFinish_FE7D6DAC460EF7053D96D4BD3B4A8EAA
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::OnFinish_FE7D6DAC460EF7053D96D4BD3B4A8EAA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "OnFinish_FE7D6DAC460EF7053D96D4BD3B4A8EAA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.OnStopEmoteEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemDefinition*              MontageItemDef                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AFortPawn*                        PawnEmoting                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USOGB_PlayEmote_C::OnStopEmoteEvent(class UFortItemDefinition* MontageItemDef, class AFortPawn* PawnEmoting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "OnStopEmoteEvent");

	Params::SOGB_PlayEmote_C_OnStopEmoteEvent Parms{};

	Parms.MontageItemDef = MontageItemDef;
	Parms.PawnEmoting = PawnEmoting;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.PlayEmote
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::PlayEmote()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "PlayEmote");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.StartSpeechBubbles
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::StartSpeechBubbles()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "StartSpeechBubbles");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.TriggerSpeechBubble
// (BlueprintCallable, BlueprintEvent)

void USOGB_PlayEmote_C::TriggerSpeechBubble()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "TriggerSpeechBubble");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SOGB_PlayEmote.SOGB_PlayEmote_C.GetRandomEmoteIndexFromList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 USOGB_PlayEmote_C::GetRandomEmoteIndexFromList() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SOGB_PlayEmote_C", "GetRandomEmoteIndexFromList");

	Params::SOGB_PlayEmote_C_GetRandomEmoteIndexFromList Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

