#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeamMemberPedestal_FeatInfo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TeamMemberPedestal_FeatInfo.TeamMemberPedestal_FeatInfo_C
// 0x0010 (0x1080 - 0x1070)
class UTeamMemberPedestal_FeatInfo_C final : public UFortTeamMemberPedestalFeatInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1070(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FeatInfoSet;                                       // 0x1078(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TeamMemberPedestal_FeatInfo(int32 EntryPoint);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void OnFeatDefinitionSet();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TeamMemberPedestal_FeatInfo_C">();
	}
	static class UTeamMemberPedestal_FeatInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamMemberPedestal_FeatInfo_C>();
	}
};
static_assert(alignof(UTeamMemberPedestal_FeatInfo_C) == 0x000010, "Wrong alignment on UTeamMemberPedestal_FeatInfo_C");
static_assert(sizeof(UTeamMemberPedestal_FeatInfo_C) == 0x001080, "Wrong size on UTeamMemberPedestal_FeatInfo_C");
static_assert(offsetof(UTeamMemberPedestal_FeatInfo_C, UberGraphFrame) == 0x001070, "Member 'UTeamMemberPedestal_FeatInfo_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UTeamMemberPedestal_FeatInfo_C, FeatInfoSet) == 0x001078, "Member 'UTeamMemberPedestal_FeatInfo_C::FeatInfoSet' has a wrong offset!");

}

