#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tree_Thick_Branchset_01

#include "Basic.hpp"

#include "Graybox_Prop_Medium_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tree_Thick_Branchset_01.Tree_Thick_Branchset_01_C
// 0x0000 (0x0E70 - 0x0E70)
class ATree_Thick_Branchset_01_C final : public AGraybox_Prop_Medium_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Tree_Thick_Branchset_01_C">();
	}
	static class ATree_Thick_Branchset_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATree_Thick_Branchset_01_C>();
	}
};
static_assert(alignof(ATree_Thick_Branchset_01_C) == 0x000008, "Wrong alignment on ATree_Thick_Branchset_01_C");
static_assert(sizeof(ATree_Thick_Branchset_01_C) == 0x000E70, "Wrong size on ATree_Thick_Branchset_01_C");

}

