#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BigGoldButton

#include "Basic.hpp"

#include "UI_BigGoldButton_classes.hpp"
#include "UI_BigGoldButton_parameters.hpp"


namespace SDK
{

// Function UI_BigGoldButton.UI_BigGoldButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UUI_BigGoldButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BigGoldButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_BigGoldButton.UI_BigGoldButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UUI_BigGoldButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BigGoldButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_BigGoldButton.UI_BigGoldButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_BigGoldButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BigGoldButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_BigGoldButton.UI_BigGoldButton_C.EventHover
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    In                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BigGoldButton_C::EventHover(bool In)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BigGoldButton_C", "EventHover");

	Params::UI_BigGoldButton_C_EventHover Parms{};

	Parms.In = In;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BigGoldButton.UI_BigGoldButton_C.ExecuteUbergraph_UI_BigGoldButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BigGoldButton_C::ExecuteUbergraph_UI_BigGoldButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BigGoldButton_C", "ExecuteUbergraph_UI_BigGoldButton");

	Params::UI_BigGoldButton_C_ExecuteUbergraph_UI_BigGoldButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BigGoldButton.UI_BigGoldButton_C.OnCurrencyUpdated
// (Event, Protected, BlueprintEvent)

void UUI_BigGoldButton_C::OnCurrencyUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BigGoldButton_C", "OnCurrencyUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_BigGoldButton.UI_BigGoldButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BigGoldButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BigGoldButton_C", "PreConstruct");

	Params::UI_BigGoldButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

