#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VaultCamera_Blueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VaultCamera_Blueprint.VaultCamera_Blueprint_C
// 0x0010 (0x09A0 - 0x0990)
class AVaultCamera_Blueprint_C final : public AFortCameraBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0990(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_VaultCamera_Blueprint(int32 EntryPoint);
	void BP_OnDeactivated(class AFortPlayerController* PlayerController);
	void BP_OnActivated(class AFortPlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VaultCamera_Blueprint_C">();
	}
	static class AVaultCamera_Blueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVaultCamera_Blueprint_C>();
	}
};
static_assert(alignof(AVaultCamera_Blueprint_C) == 0x000010, "Wrong alignment on AVaultCamera_Blueprint_C");
static_assert(sizeof(AVaultCamera_Blueprint_C) == 0x0009A0, "Wrong size on AVaultCamera_Blueprint_C");
static_assert(offsetof(AVaultCamera_Blueprint_C, UberGraphFrame) == 0x000990, "Member 'AVaultCamera_Blueprint_C::UberGraphFrame' has a wrong offset!");

}

