#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseEngine_0

#include "Basic.hpp"

#include "VerseEngine_0_classes.hpp"
#include "VerseEngine_0_parameters.hpp"


namespace SDK
{

// Function VerseEngine.Asset.$InitCDO
// ()

void UAsset::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Asset", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.Asset.$InitInstance
// ()

void UAsset::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Asset", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.Asset._L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RAsync__Load
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UAsset::_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RAsync__Load(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Asset", "_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RAsync__Load");

	Params::Asset__L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RAsync__Load Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.Asset._L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAssetType
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UAsset::_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAssetType(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Asset", "_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAssetType");

	Params::Asset__L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAssetType Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.Asset._L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAsyncLoadEvent
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UAsset::_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAsyncLoadEvent(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Asset", "_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAsyncLoadEvent");

	Params::Asset__L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RGetAsyncLoadEvent Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.Asset._L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RSyncLoad
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 UAsset::_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RSyncLoad(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Asset", "_L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RSyncLoad");

	Params::Asset__L_2fVerse_2eorg_2fVerseEngine_2fAssets_2fasset_N_RSyncLoad Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.client_asset.$InitCDO
// ()

void Uclient_asset::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("client_asset", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.client_asset.$InitInstance
// ()

void Uclient_asset::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("client_asset", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.Animation.$InitCDO
// ()

void UAnimation::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Animation", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.Animation.$InitInstance
// ()

void UAnimation::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Animation", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.animation_blueprint.$InitCDO
// ()

void Uanimation_blueprint::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("animation_blueprint", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.animation_blueprint.$InitInstance
// ()

void Uanimation_blueprint::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("animation_blueprint", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.animation_instance.$InitCDO
// ()

void Uanimation_instance::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("animation_instance", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.animation_instance.$InitInstance
// ()

void Uanimation_instance::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("animation_instance", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.Utils._L_2fVerse_2eorg_2fVerseEngine_2fUtils_N_RGetServerTime
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// double                                  RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UUtils::_L_2fVerse_2eorg_2fVerseEngine_2fUtils_N_RGetServerTime(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Utils", "_L_2fVerse_2eorg_2fVerseEngine_2fUtils_N_RGetServerTime");

	Params::Utils__L_2fVerse_2eorg_2fVerseEngine_2fUtils_N_RGetServerTime Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.Utils.Wait_L_Nfloat_R
// (Final, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class Utask*                            __verse_0xC1E81372_CallingTask                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   __verse_0xA3A00DDB_CallerResumeState                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   __verse_0x2AC0E4D8_CallerCancelState                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class Utask*                            RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class Utask* UUtils::Wait_L_Nfloat_R(class Utask* __verse_0xC1E81372_CallingTask, int64 __verse_0xA3A00DDB_CallerResumeState, int64 __verse_0x2AC0E4D8_CallerCancelState, double __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Utils", "Wait_L_Nfloat_R");

	Params::Utils_Wait_L_Nfloat_R Parms{};

	Parms.__verse_0xC1E81372_CallingTask = __verse_0xC1E81372_CallingTask;
	Parms.__verse_0xA3A00DDB_CallerResumeState = __verse_0xA3A00DDB_CallerResumeState;
	Parms.__verse_0x2AC0E4D8_CallerCancelState = __verse_0x2AC0E4D8_CallerCancelState;
	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Utils.WaitForever
// (Final, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class Utask*                            __verse_0xC1E81372_CallingTask                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   __verse_0xA3A00DDB_CallerResumeState                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   __verse_0x2AC0E4D8_CallerCancelState                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class Utask*                            RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class Utask* UUtils::WaitForever(class Utask* __verse_0xC1E81372_CallingTask, int64 __verse_0xA3A00DDB_CallerResumeState, int64 __verse_0x2AC0E4D8_CallerCancelState, const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Utils", "WaitForever");

	Params::Utils_WaitForever Parms{};

	Parms.__verse_0xC1E81372_CallingTask = __verse_0xC1E81372_CallingTask;
	Parms.__verse_0xA3A00DDB_CallerResumeState = __verse_0xA3A00DDB_CallerResumeState;
	Parms.__verse_0x2AC0E4D8_CallerCancelState = __verse_0x2AC0E4D8_CallerCancelState;
	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Utils.WaitNext
// (Final, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class Utask*                            __verse_0xC1E81372_CallingTask                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   __verse_0xA3A00DDB_CallerResumeState                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   __verse_0x2AC0E4D8_CallerCancelState                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class Utask*                            RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class Utask* UUtils::WaitNext(class Utask* __verse_0xC1E81372_CallingTask, int64 __verse_0xA3A00DDB_CallerResumeState, int64 __verse_0x2AC0E4D8_CallerCancelState, const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Utils", "WaitNext");

	Params::Utils_WaitNext Parms{};

	Parms.__verse_0xC1E81372_CallingTask = __verse_0xC1E81372_CallingTask;
	Parms.__verse_0xA3A00DDB_CallerResumeState = __verse_0xA3A00DDB_CallerResumeState;
	Parms.__verse_0x2AC0E4D8_CallerCancelState = __verse_0x2AC0E4D8_CallerCancelState;
	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Utils.$InitCDO
// ()

void UUtils::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Utils", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.camera_animation.$InitCDO
// ()

void Ucamera_animation::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("camera_animation", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.camera_animation.$InitInstance
// ()

void Ucamera_animation::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("camera_animation", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.Context_Utils$Wait_L_Nfloat_R.Update
// (Native, Public, HasOutParams)
// Parameters:
// int64                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int64 UContext_Utils_Wait_L_Nfloat_R::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Context_Utils$Wait_L_Nfloat_R", "Update");

	Params::Context_Utils_Wait_L_Nfloat_R_Update Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.Context_Utils$WaitForever.Update
// (Native, Public, HasOutParams)
// Parameters:
// int64                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int64 UContext_Utils_WaitForever::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Context_Utils$WaitForever", "Update");

	Params::Context_Utils_WaitForever_Update Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.multicast_delegate_base.$InitCDO
// ()

void Umulticast_delegate_base::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("multicast_delegate_base", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.multicast_delegate_base.$InitInstance
// ()

void Umulticast_delegate_base::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("multicast_delegate_base", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.Context_Utils$WaitNext.Update
// (Native, Public, HasOutParams)
// Parameters:
// int64                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int64 UContext_Utils_WaitNext::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Context_Utils$WaitNext", "Update");

	Params::Context_Utils_WaitNext_Update Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.curve_float.$InitCDO
// ()

void Ucurve_float::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("curve_float", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.curve_float.$InitInstance
// ()

void Ucurve_float::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("curve_float", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.curve_float._L_2fVerse_2eorg_2fVerseEngine_2fUtils_2fcurve__float_N_RGetValueAtTime_L_Nfloat_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// double                                  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double Ucurve_float::_L_2fVerse_2eorg_2fVerseEngine_2fUtils_2fcurve__float_N_RGetValueAtTime_L_Nfloat_R(double __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("curve_float", "_L_2fVerse_2eorg_2fVerseEngine_2fUtils_2fcurve__float_N_RGetValueAtTime_L_Nfloat_R");

	Params::curve_float__L_2fVerse_2eorg_2fVerseEngine_2fUtils_2fcurve__float_N_RGetValueAtTime_L_Nfloat_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugArrow_L_Nvector3_M_Nvector3_M_Narrow__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mvector3_Marrow__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugArrow_L_Nvector3_M_Nvector3_M_Narrow__draw__params_R(const struct Ftuple_Lvector3_Mvector3_Marrow__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugArrow_L_Nvector3_M_Nvector3_M_Narrow__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugArrow_L_Nvector3_M_Nvector3_M_Narrow__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugBox_L_Nvector3_M_Nrotation_M_Nbox__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mrotation_Mbox__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugBox_L_Nvector3_M_Nrotation_M_Nbox__draw__params_R(const struct Ftuple_Lvector3_Mrotation_Mbox__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugBox_L_Nvector3_M_Nrotation_M_Nbox__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugBox_L_Nvector3_M_Nrotation_M_Nbox__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCapsule_L_Nvector3_M_Nrotation_M_Ncapsule__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mrotation_Mcapsule__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCapsule_L_Nvector3_M_Nrotation_M_Ncapsule__draw__params_R(const struct Ftuple_Lvector3_Mrotation_Mcapsule__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCapsule_L_Nvector3_M_Nrotation_M_Ncapsule__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCapsule_L_Nvector3_M_Nrotation_M_Ncapsule__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCone_L_Nvector3_M_Nvector3_M_Ncone__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mvector3_Mcone__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCone_L_Nvector3_M_Nvector3_M_Ncone__draw__params_R(const struct Ftuple_Lvector3_Mvector3_Mcone__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCone_L_Nvector3_M_Nvector3_M_Ncone__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCone_L_Nvector3_M_Nvector3_M_Ncone__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCylinder_L_Nvector3_M_Nvector3_M_Ncylinder__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mvector3_Mcylinder__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCylinder_L_Nvector3_M_Nvector3_M_Ncylinder__draw__params_R(const struct Ftuple_Lvector3_Mvector3_Mcylinder__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCylinder_L_Nvector3_M_Nvector3_M_Ncylinder__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugCylinder_L_Nvector3_M_Nvector3_M_Ncylinder__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugLine_L_Nvector3_M_Nvector3_M_Nline__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mvector3_Mline__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugLine_L_Nvector3_M_Nvector3_M_Nline__draw__params_R(const struct Ftuple_Lvector3_Mvector3_Mline__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugLine_L_Nvector3_M_Nvector3_M_Nline__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugLine_L_Nvector3_M_Nvector3_M_Nline__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugPoint_L_Nvector3_M_Npoint__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mpoint__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugPoint_L_Nvector3_M_Npoint__draw__params_R(const struct Ftuple_Lvector3_Mpoint__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugPoint_L_Nvector3_M_Npoint__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugPoint_L_Nvector3_M_Npoint__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugSphere_L_Nvector3_M_Nsphere__draw__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Msphere__draw__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugSphere_L_Nvector3_M_Nsphere__draw__params_R(const struct Ftuple_Lvector3_Msphere__draw__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugSphere_L_Nvector3_M_Nsphere__draw__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RDrawDebugSphere_L_Nvector3_M_Nsphere__draw__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_Rlog__channel__handle_L_N_Kchar_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// FVerseStringProperty_                   __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// struct Flog_channel_handle              RetVal                                                 (Parm, OutParm, ReturnParm)

struct Flog_channel_handle UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_Rlog__channel__handle_L_N_Kchar_R(FVerseStringProperty_ __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_Rlog__channel__handle_L_N_Kchar_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_Rlog__channel__handle_L_N_Kchar_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_L_Kchar_Mlog__params_R    __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__params_R(const struct Ftuple_L_Kchar_Mlog__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__screen__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Ftuple_L_Kchar_Mlog__screen__params_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__screen__params_R(const struct Ftuple_L_Kchar_Mlog__screen__params_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__screen__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_M_Nlog__screen__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_R
// (Final, Static, Public, HasDefaults, BlueprintCallable)
// Parameters:
// FVerseStringProperty_                   __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_R(FVerseStringProperty_ __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLog_L_N_Kchar_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack
// (Final, Static, Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Flog_params                      __verse_0xB2CDDD72_Argument                            (Parm)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__params_R(const struct Flog_params& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics._L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__screen__params_R
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// struct Flog_screen_params               __verse_0xB2CDDD72_Argument                            (Parm)

void UDiagnostics::_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__screen__params_R(const struct Flog_screen_params& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "_L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__screen__params_R");

	Params::Diagnostics__L_2fVerse_2eorg_2fVerseEngine_2fDiagnostics_N_RLogCallstack_L_Nlog__screen__params_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.Diagnostics.arrow_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Farrow_draw_params               RetVal                                                 (Parm, OutParm, ReturnParm)

struct Farrow_draw_params UDiagnostics::arrow_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "arrow_draw_params$Factory");

	Params::Diagnostics_arrow_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.box_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Fbox_draw_params                 RetVal                                                 (Parm, OutParm, ReturnParm)

struct Fbox_draw_params UDiagnostics::box_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "box_draw_params$Factory");

	Params::Diagnostics_box_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.capsule_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Fcapsule_draw_params             RetVal                                                 (Parm, OutParm, ReturnParm)

struct Fcapsule_draw_params UDiagnostics::capsule_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "capsule_draw_params$Factory");

	Params::Diagnostics_capsule_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.cone_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Fcone_draw_params                RetVal                                                 (Parm, OutParm, ReturnParm)

struct Fcone_draw_params UDiagnostics::cone_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "cone_draw_params$Factory");

	Params::Diagnostics_cone_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.cylinder_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Fcylinder_draw_params            RetVal                                                 (Parm, OutParm, ReturnParm)

struct Fcylinder_draw_params UDiagnostics::cylinder_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "cylinder_draw_params$Factory");

	Params::Diagnostics_cylinder_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.line_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Fline_draw_params                RetVal                                                 (Parm, OutParm, ReturnParm)

struct Fline_draw_params UDiagnostics::line_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "line_draw_params$Factory");

	Params::Diagnostics_line_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.log_channel_handle$Factory
// (Static, HasOutParams)
// Parameters:
// struct Flog_channel_handle              RetVal                                                 (Parm, OutParm, ReturnParm)

struct Flog_channel_handle UDiagnostics::log_channel_handle_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "log_channel_handle$Factory");

	Params::Diagnostics_log_channel_handle_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.log_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Flog_params                      RetVal                                                 (Parm, OutParm, ReturnParm)

struct Flog_params UDiagnostics::log_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "log_params$Factory");

	Params::Diagnostics_log_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.log_screen_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Flog_screen_params               RetVal                                                 (Parm, OutParm, ReturnParm)

struct Flog_screen_params UDiagnostics::log_screen_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "log_screen_params$Factory");

	Params::Diagnostics_log_screen_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.point_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Fpoint_draw_params               RetVal                                                 (Parm, OutParm, ReturnParm)

struct Fpoint_draw_params UDiagnostics::point_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "point_draw_params$Factory");

	Params::Diagnostics_point_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.sphere_draw_params$Factory
// (Static, HasOutParams, HasDefaults)
// Parameters:
// struct Fsphere_draw_params              RetVal                                                 (Parm, OutParm, ReturnParm)

struct Fsphere_draw_params UDiagnostics::sphere_draw_params_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Diagnostics", "sphere_draw_params$Factory");

	Params::Diagnostics_sphere_draw_params_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.Diagnostics.$InitCDO
// ()

void UDiagnostics::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Diagnostics", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.skeletal_mesh.$InitCDO
// ()

void Uskeletal_mesh::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("skeletal_mesh", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.skeletal_mesh.$InitInstance
// ()

void Uskeletal_mesh::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("skeletal_mesh", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.entity_v.$InitCDO
// ()

void Uentity_v::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.entity_v.$InitInstance
// ()

void Uentity_v::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RAddComponent_L_Ntype_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UClass*                           __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RAddComponent_L_Ntype_R(class UClass* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RAddComponent_L_Ntype_R");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RAddComponent_L_Ntype_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RDestroy
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RDestroy(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RDestroy");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RDestroy Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_REnsureComponents_L_N_Ksubtype_Lcomponent_R_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// TArray<class UClass*>                   __verse_0xB2CDDD72_Argument                            (Parm)

void Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_REnsureComponents_L_N_Ksubtype_Lcomponent_R_R(const TArray<class UClass*>& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_REnsureComponents_L_N_Ksubtype_Lcomponent_R_R");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_REnsureComponents_L_N_Ksubtype_Lcomponent_R_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetAllComponentsOfType_L_Ntype_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UClass*                           __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UEntityComponent*>         RetVal                                                 (Parm, OutParm, ReturnParm)

TArray<class UEntityComponent*> Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetAllComponentsOfType_L_Ntype_R(class UClass* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetAllComponentsOfType_L_Ntype_R");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetAllComponentsOfType_L_Ntype_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetComponentOfType_L_Ntype_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UClass*                           __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetComponentOfType_L_Ntype_R(class UClass* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetComponentOfType_L_Ntype_R");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetComponentOfType_L_Ntype_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetFullname
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FVerseStringProperty_                   RetVal                                                 (Parm, OutParm, ReturnParm, HasGetValueTypeHash)

FVerseStringProperty_ Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetFullname(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetFullname");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetFullname Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetName
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FVerseStringProperty_                   RetVal                                                 (Parm, OutParm, ReturnParm, HasGetValueTypeHash)

FVerseStringProperty_ Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetName(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetName");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetName Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetOrCreateComponentOfType_L_Ntype_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UClass*                           __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetOrCreateComponentOfType_L_Ntype_R(class UClass* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetOrCreateComponentOfType_L_Ntype_R");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RGetOrCreateComponentOfType_L_Ntype_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RHasComponents_L_N_Ksubtype_Lcomponent_R_R
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// TArray<class UClass*>                   __verse_0xB2CDDD72_Argument                            (Parm)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RHasComponents_L_N_Ksubtype_Lcomponent_R_R(const TArray<class UClass*>& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RHasComponents_L_N_Ksubtype_Lcomponent_R_R");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RHasComponents_L_N_Ksubtype_Lcomponent_R_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.entity_v._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RRemoveComponent_L_Ncomponent_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UEntityComponent*                 __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 Uentity_v::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RRemoveComponent_L_Ncomponent_R(class UEntityComponent* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("entity_v", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RRemoveComponent_L_Ncomponent_R");

	Params::entity_v__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fentity__v_N_RRemoveComponent_L_Ncomponent_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.EntityHelpers._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RDestroyObject_L_Ncomponent_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UEntityComponent*                 __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 UEntityHelpers::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RDestroyObject_L_Ncomponent_R(class UEntityComponent* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EntityHelpers", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RDestroyObject_L_Ncomponent_R");

	Params::EntityHelpers__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RDestroyObject_L_Ncomponent_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.EntityHelpers._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetComponentOfTypeC_L_Ncomponent_M_Ntype_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_Lcomponent_Mtype_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UEntityHelpers::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetComponentOfTypeC_L_Ncomponent_M_Ntype_R(const struct VerseEngine_0::Ftuple_Lcomponent_Mtype_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EntityHelpers", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetComponentOfTypeC_L_Ncomponent_M_Ntype_R");

	Params::EntityHelpers__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetComponentOfTypeC_L_Ncomponent_M_Ntype_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.EntityHelpers._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetEntityFromComponent_L_Ncomponent_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UEntityComponent*                 __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UEntityHelpers::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetEntityFromComponent_L_Ncomponent_R(class UEntityComponent* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EntityHelpers", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetEntityFromComponent_L_Ncomponent_R");

	Params::EntityHelpers__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RGetEntityFromComponent_L_Ncomponent_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.EntityHelpers._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Ntransform__v_M_N_Kchar_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_Ltransform__v_M_Kchar_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UEntityHelpers::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Ntransform__v_M_N_Kchar_R(const struct VerseEngine_0::Ftuple_Ltransform__v_M_Kchar_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EntityHelpers", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Ntransform__v_M_N_Kchar_R");

	Params::EntityHelpers__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Ntransform__v_M_N_Kchar_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.EntityHelpers._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_N_Kchar_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_Lvector3_M_Kchar_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UEntityHelpers::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_N_Kchar_R(const struct VerseEngine_0::Ftuple_Lvector3_M_Kchar_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EntityHelpers", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_N_Kchar_R");

	Params::EntityHelpers__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_N_Kchar_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.EntityHelpers._L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_Nvector3_M_Nvector3_M_N_Kchar_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lvector3_Mvector3_Mvector3_M_Kchar_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ UEntityHelpers::_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_Nvector3_M_Nvector3_M_N_Kchar_R(const struct Ftuple_Lvector3_Mvector3_Mvector3_M_Kchar_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EntityHelpers", "_L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_Nvector3_M_Nvector3_M_N_Kchar_R");

	Params::EntityHelpers__L_2fVerse_2eorg_2fVerseEngine_2fEntity__V_2fEntityHelpers_N_RSpawnEntity_L_Nvector3_M_Nvector3_M_Nvector3_M_N_Kchar_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.EntityHelpers.$InitCDO
// ()

void UEntityHelpers::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EntityHelpers", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.VerseEngine._L_2fVerse_2eorg_2fVerseEngine_N_RInvalidDelegateHandle
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// struct Fdelegate_handle                 RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor)

struct Fdelegate_handle UVerseEngine::_L_2fVerse_2eorg_2fVerseEngine_N_RInvalidDelegateHandle(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("VerseEngine", "_L_2fVerse_2eorg_2fVerseEngine_N_RInvalidDelegateHandle");

	Params::VerseEngine__L_2fVerse_2eorg_2fVerseEngine_N_RInvalidDelegateHandle Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.VerseEngine.delegate_handle$Factory
// (Static, HasOutParams)
// Parameters:
// struct Fdelegate_handle                 RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor)

struct Fdelegate_handle UVerseEngine::delegate_handle_Factory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("VerseEngine", "delegate_handle$Factory");

	Params::VerseEngine_delegate_handle_Factory Parms{};

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseEngine.VerseEngine.$InitCDO
// ()

void UVerseEngine::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VerseEngine", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.font_v.$InitCDO
// ()

void Ufont_v::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("font_v", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.font_v.$InitInstance
// ()

void Ufont_v::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("font_v", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.level_v.$InitCDO
// ()

void Ulevel_v::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("level_v", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.level_v.$InitInstance
// ()

void Ulevel_v::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("level_v", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.material_v.$InitCDO
// ()

void Umaterial_v::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("material_v", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.material_v.$InitInstance
// ()

void Umaterial_v::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("material_v", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.float_param_multicast_delegate.$InitCDO
// ()

void Ufloat_param_multicast_delegate::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("float_param_multicast_delegate", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.float_param_multicast_delegate.$InitInstance
// ()

void Ufloat_param_multicast_delegate::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("float_param_multicast_delegate", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.float_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RBroadcast_L_Nfloat_R
// (Native, Public, BlueprintCallable)
// Parameters:
// double                                  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ufloat_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RBroadcast_L_Nfloat_R(double __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("float_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RBroadcast_L_Nfloat_R");

	Params::float_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RBroadcast_L_Nfloat_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.float_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_REmpty
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void Ufloat_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_REmpty(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("float_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_REmpty");

	Params::float_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_REmpty Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.float_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RSubscribe_L_Nfloat_Tvoid_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TDelegate<void(double __verse_0xB2CDDD72_Argument)>__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct Fdelegate_handle                 RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor)

struct Fdelegate_handle Ufloat_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RSubscribe_L_Nfloat_Tvoid_R(TDelegate<void(double __verse_0xB2CDDD72_Argument)> __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("float_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RSubscribe_L_Nfloat_Tvoid_R");

	Params::float_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RSubscribe_L_Nfloat_Tvoid_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.float_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Fdelegate_handle                 __verse_0xB2CDDD72_Argument                            (Parm, NoDestructor)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Ufloat_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R(const struct Fdelegate_handle& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("float_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R");

	Params::float_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2ffloat__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.int_param_multicast_delegate.$InitCDO
// ()

void Uint_param_multicast_delegate::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("int_param_multicast_delegate", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.int_param_multicast_delegate.$InitInstance
// ()

void Uint_param_multicast_delegate::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("int_param_multicast_delegate", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.int_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RBroadcast_L_Nint_R
// (Native, Public, BlueprintCallable)
// Parameters:
// int64                                   __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uint_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RBroadcast_L_Nint_R(int64 __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("int_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RBroadcast_L_Nint_R");

	Params::int_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RBroadcast_L_Nint_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.int_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_REmpty
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void Uint_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_REmpty(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("int_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_REmpty");

	Params::int_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_REmpty Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.int_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RSubscribe_L_Nint_Tvoid_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TDelegate<void(int64 __verse_0xB2CDDD72_Argument)>__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct Fdelegate_handle                 RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor)

struct Fdelegate_handle Uint_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RSubscribe_L_Nint_Tvoid_R(TDelegate<void(int64 __verse_0xB2CDDD72_Argument)> __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("int_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RSubscribe_L_Nint_Tvoid_R");

	Params::int_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RSubscribe_L_Nint_Tvoid_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.int_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Fdelegate_handle                 __verse_0xB2CDDD72_Argument                            (Parm, NoDestructor)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Uint_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R(const struct Fdelegate_handle& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("int_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R");

	Params::int_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fint__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.logic_param_multicast_delegate.$InitCDO
// ()

void Ulogic_param_multicast_delegate::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("logic_param_multicast_delegate", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.logic_param_multicast_delegate.$InitInstance
// ()

void Ulogic_param_multicast_delegate::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("logic_param_multicast_delegate", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.logic_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RBroadcast_L_Nlogic_R
// (Native, Public, BlueprintCallable)
// Parameters:
// uint8                                   __verse_0xB2CDDD72_Argument                            (Parm, NoDestructor, HasGetValueTypeHash)

void Ulogic_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RBroadcast_L_Nlogic_R(uint8 __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("logic_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RBroadcast_L_Nlogic_R");

	Params::logic_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RBroadcast_L_Nlogic_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.logic_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_REmpty
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void Ulogic_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_REmpty(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("logic_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_REmpty");

	Params::logic_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_REmpty Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.logic_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RSubscribe_L_Nlogic_Tvoid_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TDelegate<void(uint8 __verse_0xB2CDDD72_Argument)>__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct Fdelegate_handle                 RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor)

struct Fdelegate_handle Ulogic_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RSubscribe_L_Nlogic_Tvoid_R(TDelegate<void(uint8 __verse_0xB2CDDD72_Argument)> __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("logic_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RSubscribe_L_Nlogic_Tvoid_R");

	Params::logic_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RSubscribe_L_Nlogic_Tvoid_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.logic_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Fdelegate_handle                 __verse_0xB2CDDD72_Argument                            (Parm, NoDestructor)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Ulogic_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R(const struct Fdelegate_handle& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("logic_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R");

	Params::logic_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2flogic__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.no_param_multicast_delegate.$InitCDO
// ()

void Uno_param_multicast_delegate::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("no_param_multicast_delegate", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.no_param_multicast_delegate.$InitInstance
// ()

void Uno_param_multicast_delegate::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("no_param_multicast_delegate", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.no_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RBroadcast
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void Uno_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RBroadcast(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("no_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RBroadcast");

	Params::no_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RBroadcast Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.no_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_REmpty
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void Uno_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_REmpty(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("no_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_REmpty");

	Params::no_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_REmpty Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.no_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RSubscribe_L_Ntuple_L_R_Tvoid_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)>__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct Fdelegate_handle                 RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor)

struct Fdelegate_handle Uno_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RSubscribe_L_Ntuple_L_R_Tvoid_R(TDelegate<void(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)> __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("no_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RSubscribe_L_Ntuple_L_R_Tvoid_R");

	Params::no_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RSubscribe_L_Ntuple_L_R_Tvoid_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.no_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Fdelegate_handle                 __verse_0xB2CDDD72_Argument                            (Parm, NoDestructor)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Uno_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R(const struct Fdelegate_handle& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("no_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R");

	Params::no_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fno__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.particle_system.$InitCDO
// ()

void Uparticle_system::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("particle_system", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.particle_system.$InitInstance
// ()

void Uparticle_system::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("particle_system", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.sound.$InitCDO
// ()

void Usound::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("sound", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.sound.$InitInstance
// ()

void Usound::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("sound", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.static_mesh.$InitCDO
// ()

void Ustatic_mesh::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("static_mesh", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.static_mesh.$InitInstance
// ()

void Ustatic_mesh::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("static_mesh", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.string_param_multicast_delegate.$InitCDO
// ()

void Ustring_param_multicast_delegate::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("string_param_multicast_delegate", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.string_param_multicast_delegate.$InitInstance
// ()

void Ustring_param_multicast_delegate::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("string_param_multicast_delegate", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseEngine.string_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RBroadcast_L_N_Kchar_R
// (Native, Public, BlueprintCallable)
// Parameters:
// FVerseStringProperty_                   __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void Ustring_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RBroadcast_L_N_Kchar_R(FVerseStringProperty_ __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("string_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RBroadcast_L_N_Kchar_R");

	Params::string_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RBroadcast_L_N_Kchar_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.string_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_REmpty
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseEngine_0::Ftuple_L_R        __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void Ustring_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_REmpty(const struct VerseEngine_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("string_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_REmpty");

	Params::string_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_REmpty Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseEngine.string_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RSubscribe_L_N_Kchar_Tvoid_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TDelegate<void(FVerseStringProperty_ __verse_0xB2CDDD72_Argument)>__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct Fdelegate_handle                 RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor)

struct Fdelegate_handle Ustring_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RSubscribe_L_N_Kchar_Tvoid_R(TDelegate<void(FVerseStringProperty_ __verse_0xB2CDDD72_Argument)> __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("string_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RSubscribe_L_N_Kchar_Tvoid_R");

	Params::string_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RSubscribe_L_N_Kchar_Tvoid_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function VerseEngine.string_param_multicast_delegate._L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Fdelegate_handle                 __verse_0xB2CDDD72_Argument                            (Parm, NoDestructor)
// FOptionProperty_                        RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

FOptionProperty_ Ustring_param_multicast_delegate::_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R(const struct Fdelegate_handle& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("string_param_multicast_delegate", "_L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R");

	Params::string_param_multicast_delegate__L_2fVerse_2eorg_2fVerseEngine_2fstring__param__multicast__delegate_N_RUnsubscribe_L_Ndelegate__handle_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

